# Generated by Django 3.0.8 on 2020-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200723_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blogs.Tag'),
        ),
    ]
