# Generated by Django 3.0.8 on 2020-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
