# Generated by Django 3.0.8 on 2020-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('project_title', models.CharField(blank=True, max_length=500, null=True)),
                ('project_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('budget', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
