# Generated by Django 3.0.8 on 2020-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_productdevelopment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
