# Generated by Django 3.0.8 on 2020-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_auto_20200801_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
