# Generated by Django 3.0.8 on 2020-08-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_auto_20200801_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
